[package]
name = "soul_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
parser_models = { version = "0.1.0", path = "models" }
soul_tokenizer = { version = "0.1.0", path = "../soul_tokenizer" }
soul_utils = { version = "0.1.0", path = "../soul_utils" }
