[package]
name = "soul_name_resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
ast = { version = "0.1.0", path = "../../soul_ast/ast_model" }
soul_utils = { version = "0.1.0", path = "../../soul_utils" }
