[package]
name = "soul_hir"
version = "0.1.0"
edition = "2024"

[dependencies]
soul_ast = {path = "../soul_ast"}
serde = {version = "1.0.228", features = ["derive"]}
soul_utils = {path = "../soul_utils"}
