[package]
name = "ast_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ast = { version = "0.1.0", path = "../ast_model" }
soul_tokenizer = { version = "0.1.0", path = "../../soul_tokenizer" }
soul_utils = { version = "0.1.0", path = "../../soul_utils" }
