[package]
name = "soul_tester"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde_cbor = "0.11.2"
serde_json = "1.0.148"
soul_ast = {path = "../soul_ast"}
hir_converter = {path = "../hir_converter"}
ast_converter = {path = "../ast_converter"}
serde = {version = "1.0.228", features = ["derive"]}
