[package]
name = "soul_tester"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde_json = "1.0.148"
serde = {version = "1.0.228", features = ["derive"]}
soul_name_resolver = { version = "0.1.0", path = "../soul_sementic/soul_name_resolver" }
parser_models = { version = "0.1.0", path = "../soul_parser/models" }
soul_tokenizer = { version = "0.1.0", path = "../soul_tokenizer" }
soul_parser = { version = "0.1.0", path = "../soul_parser" }
soul_utils = { version = "0.1.0", path = "../soul_utils", features=["absolute_internal_error_path"]}
