[package]
name = "soul_tester"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.148"
soul_tokenizer = {path = "../soul_tokenizer"}
soul_utils = {path = "../soul_utils"}
