[package]
name = "ast_converter"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
soul_ast = {path = "../soul_ast"}
soul_utils = {path = "../soul_utils"}
serde = {version = "1.0.228", features = ["derive"]}